🎵 Implement deserialization for ogg files
beardgame/audio pull request #72
Opened 2022-10-15 12:31 UTC by tomrijnbeek

## ✨ What's this?
This PR adds support for extracting sound buffer data from OGG files, including a snapshot test.

### 🔗 Relationships
Closes #8 

## 🔍 Why do we want this?
OGG is an open format and is commonly used for compressed audio.

## 🏗 How is it done?
The deserialization is largely done by the NVorbis library, so logically this PR is pretty straightforward. After looking at NAudio, a different audio library not built on OpenAL, I kinda like the idea of putting the actual file parsing logic in a separate class. The idea is that this class is a stateful object, so it can be used to stream the files rather than loading the entire file in memory at once.

My intent is to have a future PR migrate the wave file loading to a similar class. Hopefully we can extract a common interface, and have some streaming loading logic layer on top of that interface, so that the streaming can be applied to any file format you may use, as long as you have a stream for that file type.

All in all, I am aware that this is _very_ WIP, and it wouldn't surprise me if there will be several changes to the underlying logic, though having the current static methods to load as convenience method is not something that will go away quickly. I have left the `OggStream` class as internal for the time being while we work on this.

### 💥 Breaking changes
None.

### 🔬 Why not another way?
The current approach opens up the use cases I want to support (particularly streaming in #17), and contributes to a better reusable framework (see #16). There are probably other solutions, but this one seems the best for the time being. We probably need to start using this to get a better sense of what works and what doesn't, so I'd like to commit to this approach from now, and take this a bit agile.

### 🦋 Side effects
WAV file loading needs to be migrated. Will create an issue if this PR is approved to validate the approach.

## 💡 Review hints
`Stream` is a super overloaded term, so open to suggestions for better naming. `Reader` is a possibility, though also very vague. `Decoder` doesn't really imply that it's holding the lock to a file open.

2022-10-15 14:21 UTC, paulcscharf requested changes
Looks mostly fine. Left some comments to consider.

2022-10-15 14:21 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggStream.cs
> +        var floatBuffer = new float[largestBufferSizeDivisibleByChannelCount(maxBufferSize)];
Can we do anything to prevent reallocation of this temporary array? Or can we perhaps allocate it on the stack?

2022-10-15 14:21 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggStream.cs
> +        buffer = new short[numSamplesRead];
I'm not asking to change it now, but it would be great if we can later read into a set of provided buffers instead of allocations new ones.

2022-10-15 14:21 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggStream.cs
> +            TryReadSingleBuffer(out var buffer, maxBufferSize);
I think this method repeats some of the checks and calculations - perhaps we can extract a common private method for the actual reading from the reader?

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +sealed class OggStream : IDisposable
Fair enough, renamed.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +    public bool Ended => reader.IsEndOfStream;
`StreamReader` calls this `EndOfStream`, `StringReader` and `BinaryReader` don't have it, and `Stream` itself only exposes the position and length, so you have to do it yourself. The `VorbisReader` from NVorbis uses `IsEndOfStream` as you can see. So... really no consistency there.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +    public IList<short[]> ReadAllRemainingBuffers(int maxBufferSize)
You're completely right.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        var totalBuffersNeeded = (int) fullBuffers + partialBuffers;
Yes. I changed this to do the overflow check after the addition instead.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        if (fullBuffers > int.MaxValue)
I don't see why not. The max buffer size can be anything really (though is typically a few thousand), and the vorbis reader tracks the number of buffers in a long, not an integer. A very long file could in principle go over this limit.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        }).ToImmutableArray();
Good shout, done.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        if (reader.IsEndOfStream)
Done

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        buffer = new short[numSamplesRead];
Agreed. Since sound buffer data is immutable though, right now you'll always have to allocate an array somewhere, so might as well keep it here for now.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        var floatBuffer = new float[largestBufferSizeDivisibleByChannelCount(maxBufferSize)];
I have now been introduced to the wonders of `stackalloc`. That's pretty cool actually!

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +    public static OggStream FromFile(Stream file)
They use constructor overloads, which I don't like much. Using `FromStream` now.

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +        if (maxBufferSize <= 0)
Fair enough

2022-10-15 15:31 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggStream.cs
> +            TryReadSingleBuffer(out var buffer, maxBufferSize);
Refactored a bit.

2022-10-15 21:57 UTC, paulcscharf requested changes

2022-10-15 21:57 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +        return builder.ToImmutable();
I believe this still creates a copy. Use MoveToImmutable instead.

2022-10-15 21:57 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +        Span<float> floatSpan = stackalloc float[maxSampleCount];
I know it was my suggestion to try allocating on the Stack - that being said, how large can these buffers get? Variable length allocation on the stack could be quite dangerous, since by default the stack is limited to 1MB. StackOverflowExceptions beckon.

2022-10-15 21:57 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +            builder.Add(readSamples(bufferSize));
Don't we need to treat a potentially partial last buffer differently?

2022-10-15 21:57 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +    private short[] readSamples(int maxSampleCount)
The argument is called 'max', but is it now simply the sampleCount at this point? (or even just 'count' given the context of the method)

2022-10-15 22:01 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +        Span<float> floatSpan = stackalloc float[maxSampleCount];
If we expect the sample count to be relatively low in most cases, you could always do something like
```cs
const int maxStackAllocCount = 256;
Span<float> buffer =
    maxSampleCount > maxStackAllocCount 
      ? new float[maxSampleCount]
      : stackalloc byte[maxSampleCount]; // or perhaps even [maxStackAllocCount] (+ slice)? not sure if there's a reason using a constant is strictly better
```

2022-10-16 12:18 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggReader.cs
> +        return builder.ToImmutable();
Confusing naming. Done

2022-10-16 12:19 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggReader.cs
> +    private short[] readSamples(int maxSampleCount)
We may be reading fewer samples than the actual sample count, if we are filling the last partial buffer. In other words, `numSamplesRead` (renamed to `readSampleCount` now for consistency in naming) can be less than or equal to `maxSampleCount`, I have now called it `sampleCount`, but it should be noted that the number of samples returned may be fewer than the specified parameter.

2022-10-16 12:20 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggReader.cs
> +            builder.Add(readSamples(bufferSize));
The `readSamples` already handles the partial buffer correctly.

2022-10-16 12:22 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggReader.cs
> +        Span<float> floatSpan = stackalloc float[maxSampleCount];
As discussed offline, changed this to reuse a float buffer.

2022-10-16 14:20 UTC, paulcscharf commented on src/Bearded.Audio/Core/OggReader.cs
> +            builder.Add(readSamples(bufferSize));
I see - I did not realise that Reader.ReadSamples did this automatically. I was looking at the array/spam allocation and couldn't find it there. It's fine then (and so was the name of the readSamples parameter) though it is perhaps slightly unfortunate that we may allocate a big float array even if we are only gonna use a part of it.

2022-10-16 14:21 UTC, paulcscharf approved these changes

2022-10-16 14:22 UTC, tomrijnbeek commented on src/Bearded.Audio/Core/OggReader.cs
> +            builder.Add(readSamples(bufferSize));
Sadly that's the way it is, and we try to limit this problem by not making the buffer size _too_ big. In practice - especially for ogg files - the files will hopefully be so long that most of the time you're filling at least a few buffers fully.

2022-10-16 14:22 UTC, merged